
public class AVL_Tester {
	public static void main(String[] args){
		long startTime = System.currentTimeMillis();
		
		
		AVLSearchTree b = new AVLSearchTree(50);
		AVLTreePrinter tree = new AVLTreePrinter(b);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");		
		b.add(30);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(15);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(13);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(12);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(60);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(40);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(65);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(87);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(99);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(45);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(76);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(73);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(71);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(75);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(72);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(57);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(27);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(21);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(23);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(25);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(28);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(92);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(82);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(63);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(84);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(95);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(98);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(39);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(23);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(85);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(99);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");	
		b.add(46);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(44);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		b.add(47);
		tree = new AVLTreePrinter(b);
		tree.print("AVL");
		
		b.remove(65);
		tree.print("AVL Removed root");	
		b.remove(71);
		tree.print("AVL Removed root");	
		b.remove(72);
		tree.print("AVL Removed root");	
		b.remove(73);
		tree.print("AVL Removed root");
		b.remove(75);
		tree.print("AVL Removed root");	
		b.remove(76);
		tree.print("AVL Removed root");	
		b.remove(82);
		tree.print("AVL Removed root");	
		b.remove(84);
		tree.print("AVL Removed root");	
		b.remove(85);
		tree.print("AVL Removed root");	
		b.remove(40);
		tree.print("AVL Removed root");	
		b.remove(44);
		tree.print("AVL Removed root");	
		b.remove(45);
		tree.print("AVL Removed root");	
		b.remove(46);
		tree.print("AVL Removed root");	
		b.remove(47);
		tree.print("AVL Removed root");
		b.remove(50);
		tree.print("AVL Removed root");
		b.remove(57);
		tree.print("AVL Removed root");	
		b.remove(60);
		tree.print("AVL Removed root");
		b.remove(63);
		tree.print("AVL Removed root");	
		b.remove(87);
		tree.print("AVL Removed root");	
		b.remove(92);
		tree.print("AVL Removed root");	
		b.remove(95);
		tree.print("AVL Removed root");	
		b.remove(27);
		tree.print("AVL Removed root");	
		b.remove(28);
		tree.print("AVL Removed root");
		b.remove(30);
		tree.print("AVL Removed root");	
		b.remove(39);
		tree.print("AVL Removed root");	
		b.remove(98);
		tree.print("AVL Removed root");	
		b.remove(21);
		tree.print("AVL Removed root");	
		b.remove(23);
		tree.print("AVL Removed root");	
		b.remove(23);
		tree.print("AVL Removed root");	
		b.remove(25);
		tree.print("AVL Removed root");	
		b.remove(13);
		tree.print("AVL Removed root");	
		b.remove(15);
		tree.print("AVL Removed root");	
		b.remove(99);
		tree.print("AVL Removed root");
		b.remove(12);
		tree.print("AVL Removed root");	
		

	
	}
}
